//
// Created by pcernek on 6/3/15.
//

#ifndef SATENSTEIN_SATENSTEIN_TYPES_H
#define SATENSTEIN_SATENSTEIN_TYPES_H

typedef enum {
  UPDATE_G2WSAT_1 = 1,
  UPDATE_G2WSAT_2,
  UPDATE_GNOVELTYPLUS,
  UPDATE_DCCA
} PromListUpdateScheme;

typedef enum {
  PICK_FREEBIE = 1,
  PICK_BESTSCORE,
  PICK_OLDEST,
  PICK_BEST_VW1,
  PICK_BEST_VW2,
  PICK_RANDOM,
  PICK_NOVELTY,
  PICK_NOVELTYPLUSPLUS,
  PICK_NOVELTYPLUS,
  PICK_NOVELTYPLUSPLUSPRIME,
  PICK_NOVELTYPLUSP,
  PICK_DCCA
} DecPromVarPickingStrategy;

#endif //SATENSTEIN_SATENSTEIN_TYPES_H
